#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#------------------------------- nanoFluid4Foam project -------------------------------#
#Author
    #Ehsan Golab, SUT. All rights reserved.
    #Ehsan1996Golab@gmail.com

#--------------------------------------------------------------------------------------#

# cleancase is function that removes the files and directories.
cleancase () {
rm -f fluidDomain.fms
rm -r processor*
}

# (getApplication) is an command to find the solver name from the controlDict file. Also, ($) use for the variable.
application=$(getApplication)

#to remove the files and directories befor rendering.
cleancase
./Allclean

echo meshing...
surfaceFeatureEdges fluidDomain.stl fluidDomain.fms
cartesianMesh
autoPatch 80 -overwrite
createPatch -overwrite
transformPoints -scale '(0.001 0.001 0.001)'
checkMesh

echo run solver ...
$application

# -------------------------------------------------------------------------- end-of-file
